
package ex0009;

import java.time.LocalDateTime;


public class Dlg extends javax.swing.JDialog
{
  private boolean ok;

  public boolean isOk()
  {
    return ok;
  }
  
  public Messwert getMesswert()
  {
    double wert = Double.parseDouble(tfTemperatur.getText());
    LocalDateTime ldt = LocalDateTime.parse(tfZeitpunkt.getText());
    String k = tfKommentar.getText();
    return new Messwert(wert,ldt,k);
  }
  
  public Dlg(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
    ok = false;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfTemperatur = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    tfZeitpunkt = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    tfKommentar = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Messwert hinzufügen");

    jPanel1.setLayout(new java.awt.GridLayout(3, 2));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Temperaturwert");
    jPanel1.add(jLabel1);

    tfTemperatur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    tfTemperatur.setText("22.0");
    jPanel1.add(tfTemperatur);

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Zeitpunkt der Erfasssung");
    jPanel1.add(jLabel2);

    tfZeitpunkt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    tfZeitpunkt.setText("2021-04-09T11:18:02.971");
    jPanel1.add(tfZeitpunkt);

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Kommentar");
    jPanel1.add(jLabel3);

    tfKommentar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    tfKommentar.setText("Arnfels KU Saal");
    jPanel1.add(tfKommentar);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jPanel2.setLayout(new java.awt.GridLayout());

    jButton1.setText("OK");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onOK(evt);
      }
    });
    jPanel2.add(jButton1);

    jButton2.setText("Cancel");
    jButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onCancel(evt);
      }
    });
    jPanel2.add(jButton2);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onOK(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onOK
  {//GEN-HEADEREND:event_onOK
    ok = true;
    this.setVisible(false);
  }//GEN-LAST:event_onOK

  private void onCancel(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onCancel
  {//GEN-HEADEREND:event_onCancel
    ok = false;
    this.setVisible(false);
  }//GEN-LAST:event_onCancel

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        Dlg dialog = new Dlg(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField tfKommentar;
  private javax.swing.JTextField tfTemperatur;
  private javax.swing.JTextField tfZeitpunkt;
  // End of variables declaration//GEN-END:variables
}
