
package ex0009;

import javax.swing.JOptionPane;


public class GUI extends javax.swing.JFrame
{
  private Inventory inv;
 
  public GUI()
  {
    initComponents();
    inv = new Inventory();
    this.jList1.setModel(inv);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenuItem7 = new javax.swing.JMenuItem();
    jMenuItem8 = new javax.swing.JMenuItem();
    jMenuItem9 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Messwerterfassung");

    jList1.setModel(new javax.swing.AbstractListModel<String>()
    {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(jList1);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jMenu1.setText("File");

    jMenuItem1.setText("Speichern");
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Laden");
    jMenu1.add(jMenuItem2);
    jMenu1.add(jSeparator1);

    jMenuItem3.setText("Beenden");
    jMenu1.add(jMenuItem3);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");

    jMenuItem4.setText("Hinzufügen");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAdd(evt);
      }
    });
    jMenu2.add(jMenuItem4);

    jMenuItem5.setText("Löschen");
    jMenuItem5.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onDelete(evt);
      }
    });
    jMenu2.add(jMenuItem5);

    jMenuItem6.setText("Lösche Einträge mit \"Arnfels KU Saal\"");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onRemoveEntries(evt);
      }
    });
    jMenu2.add(jMenuItem6);

    jMenuItem7.setText("Maximaler Temperaturwert");
    jMenuItem7.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onMaxTemperatureValue(evt);
      }
    });
    jMenu2.add(jMenuItem7);

    jMenuItem8.setText("Wie oft kommt der maximale Wert vor ?");
    jMenuItem8.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onCountMaxTempValues(evt);
      }
    });
    jMenu2.add(jMenuItem8);

    jMenuItem9.setText("Alle Messwert vom Jahr 2021 anzeigen");
    jMenuItem9.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onShowAllEntriesFrom2021(evt);
      }
    });
    jMenu2.add(jMenuItem9);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onDelete(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onDelete
  {//GEN-HEADEREND:event_onDelete
    int sel = this.jList1.getSelectedIndex();
    System.out.println(""+sel);
    if(sel>-1)
    {
      inv.delete(sel);
    }
  }//GEN-LAST:event_onDelete

  private void onAdd(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAdd
  {//GEN-HEADEREND:event_onAdd
    System.out.println("onAdd");
    Dlg dlg = new Dlg(this,true);
    dlg.setVisible(true);
    if(dlg.isOk())
    {
      try
      {  
        Messwert m = dlg.getMesswert();
        inv.add(m);
      }
      catch(Exception ex)
      {
        JOptionPane.showMessageDialog(this, ex, "FEHLER !!!", JOptionPane.ERROR_MESSAGE);
      }
    }
  }//GEN-LAST:event_onAdd

  private void onRemoveEntries(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onRemoveEntries
  {//GEN-HEADEREND:event_onRemoveEntries
    inv.removeEntries();
  }//GEN-LAST:event_onRemoveEntries

  private void onMaxTemperatureValue(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onMaxTemperatureValue
  {//GEN-HEADEREND:event_onMaxTemperatureValue
    double max = inv.maxTemperatureValue();
    JOptionPane.showMessageDialog(this, "<html><body><h1>MAX = "+max+"</h1></body></html>", "Maximaler Temperaturwert", JOptionPane.INFORMATION_MESSAGE);
  }//GEN-LAST:event_onMaxTemperatureValue

  private void onCountMaxTempValues(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onCountMaxTempValues
  {//GEN-HEADEREND:event_onCountMaxTempValues
    int counter = inv.countMaxTempValues();
    JOptionPane.showMessageDialog(this, "<html><body><h1>"+counter+"</h1></body></html>", "Wie oft kommt der maximale Temperaturwert vor?", JOptionPane.INFORMATION_MESSAGE);    
  }//GEN-LAST:event_onCountMaxTempValues

  private void onShowAllEntriesFrom2021(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onShowAllEntriesFrom2021
  {//GEN-HEADEREND:event_onShowAllEntriesFrom2021
    String htmlTable = inv.getAllEntriesFrom2021();
    JOptionPane.showMessageDialog(this, "<html><body>"+htmlTable+"</body></html>", "Alle Einträge vom Jahr 2021 !!!", JOptionPane.INFORMATION_MESSAGE);        
  }//GEN-LAST:event_onShowAllEntriesFrom2021

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new GUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JList<String> jList1;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JMenuItem jMenuItem8;
  private javax.swing.JMenuItem jMenuItem9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  // End of variables declaration//GEN-END:variables
}
